# Generated by Django 5.0.7 on 2024-09-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Specialisation',
            new_name='specialisation',
        ),
    ]
