# Generated by Django 5.0.7 on 2024-10-01 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrequest',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
    ]
