# Generated by Django 5.0.7 on 2024-10-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_patientrequest_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
    ]
